version: '3.7'
services:
  app:
    build:
      context: ./converter
      dockerfile: Dockerfile
    restart: always
    container_name: converter_api_app
    networks:
      - web_net 
    ports:
      - "5000:5000"
    environment:
      - DEBUG=0  
    volumes:
      - ./project:/home/ubuntu/project/data
    depends_on: 
      - db
  nginx:
    container_name: cloud_conversion_nginx
    restart: always
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - web_net
    volumes:
      - ./default.conf:/etc/nginx/conf.d/
    depends_on:
      - app
  db: 
    container_name: cloud_conversion_db
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloud_conversion
    image: "postgres:latest"
    networks:
      - web_net
    ports: 
      - "5432:5432"
    volumes: 
      - ${PWD}/postgres-data:/var/lib/postgresql/data
networks:
  web_net:
      driver: bridge
volumes: 
  pg-data: 
    driver: local