version: '3.7'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    container_name: converter_api_app
    networks:
      - web_net 
    ports:
      - "5000:5000"
    environment:
      - DEBUG=0  
    volumes:
      - .:/app
# networks:
#   web_net:
#     ipam:
#         config:
#           - subnet: 172.19.0.0/16
#     driver: bridge